name: Sole Galore
favicon: null
layout_spectrum: 0.894006336806342
typography_spectrum: 0.9417011060286313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.027841757982969284
  lightness: 0.07060417113825679
  saturation: 0.9692429406568408
  rhythmicContrast: 0.38563350727781653
purpose: []
